apiVersion: v1
kind: Pod
metadata:
  name: abcapp
  namespace: default
  labels:
    app: demo
spec:
  containers:
  - name: abccon
    image: chitrakampelli/abc_tech:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: abcsvc
  namespace: default
spec: 
  type: NodePort
  selector:
    app: demo
  ports:  
    - protocol: TCP
      port: 32000
      targetPort: 8080
